language: python
env:
  - PYTHON_VERSION=2.7
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy scipy nose flake8
  - source activate env_name
  - conda install --yes -c https://conda.anaconda.org/biocore VSEARCH MAFFT
  - pip install coveralls
  - pip install --process-dependency-links .
script:
  - nosetests --with-doctest --with-coverage
  - flake8 deblur scripts setup.py
after_success:
  - coveralls
