language: python
env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  - export TMPDIR=/tmp/deblur-testing
  - mkdir $TMPDIR
install:
  - conda create --yes -n deblur python=$PYTHON_VERSION pip nose flake8 h5py # "numpy<1.14.0,>=1.9.2"
  - source activate deblur
  - conda install --yes -c bioconda "VSEARCH>=2.0.3,<=2.7.0" MAFFT=7.310 SortMeRNA=2.0
  - pip install -U pip coveralls
  - pip install --process-dependency-links .
script:
  #- nosetests --with-doctest --with-coverage --cover-package=deblur
    # flake8 --max-line-length=200 deblur scripts/deblur setup.py
  - python /home/travis/build/biocore/deblur/deblur/test/test_workflow.py workflowTests.test_remove_chimeras_denovo_from_seqs
  - ls -lrt $TMPDIR
  - for f in $(ls -1 $TMPDIR); do echo $f; head $f; done
after_success:
  - coveralls
